config/routes.rb
Winedb::Application.routes.draw do

  root  'static_pages#home'
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/contact"
  get "static_pages/about"
  resources :countries
  resources :wines
  resources :grapes
  resources :events
  resources :reviews
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :regions
  resources :collections
  resources :consumed_wines
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/appellation.rb
class Appellation < ActiveRecord::Base
  has_many :wines
  belongs_to :country
end

app/models/consumed_wine.rb
class ConsumedWine < ActiveRecord::Base

  belongs_to :user
  belongs_to :wine
  belongs_to :currency

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :wines
  has_many :regions
  has_many :appellations
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :prices
  has_many :consumed_wines
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :wines
end

app/models/grape.rb
class Grape < ActiveRecord::Base
  has_and_belongs_to_many :wines
end

app/models/price.rb
class Price < ActiveRecord::Base
  validates :amount, presence: true
  validates :wine_id, uniqueness: true
  belongs_to :wine
  belongs_to :currency
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :wines
  belongs_to :country
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :wine
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :wines
  has_many :consumed_wines

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :password, length: { minimum: 6 }
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :country
  belongs_to :region
  belongs_to :appellation
  has_one :price
  has_and_belongs_to_many :events
  has_and_belongs_to_many :grapes
  has_many :reviews
  has_and_belongs_to_many :users
  has_many :consumed_wines

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def edit

  end

  def update

  end

  def index
    @users = User.all
  end

  def destroy

  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  def new
    @wine = Wine.new
  end

  def show
    @wine = Wine.find(params[:id])
  end

  def edit
    @wine = Wine.find(params[:id])
  end

  def create
    @wine = Wine.new(user_params)
    if @wine.save
      redirect_to @wine
    else
      render 'new'
    end
  end

  def update
    @wine = Wine.find(params[:id])

    if @wine.update(user_params)
      redirect_to @wine
    else
      render 'edit'
    end
  end

  def index
    if params[:search]
      @wines = Wine.search(params[:search]).order("created_at DESC")
    else
      @wines = Wine.order("created_at DESC")
    end
  end

  def destroy
    Wine.find(params[:id]).destroy
    flash[:success] = "Wine deleted."
    redirect_to wines_url
  end

  private

    def user_params
      params.require(:wine).permit(:name, :link, :vintage, :country_id, :region_id, :purchased_from, :appellation_id, :picture, :date_consumed, :description, :grape_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<div class="container">
  <table class="table ">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Delete</th>
    </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user_path(user.id) %></td>
      <td><%= user.email %></td>
      <td><%= link_to "Delete", user, method: :delete, data: { confirm: "You sure?" } %> | <%= link_to 'Edit User', edit_user_path(user), method: :get %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/users/new.html.erb
<HR>
<h1>Add User</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Add User", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<HR>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>ID:</strong>
  <%= current_user.id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/wines/edit.html.erb
<HR>
<h1>Edit Wine</h1>

<div class="container">
  <div class="form group">
    <%= form_for(@wine) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :vintage %>
      <%= f.text_field :vintage, class: "form-control" %>

      <%= f.label :country_id %>
      <%= f.select(:country_id,options_from_collection_for_select(Country.all, :id, :name, @wine.country_id)) %>

      <%= f.label :region_id %>
      <%= f.select(:region_id,options_from_collection_for_select(Region.all, :id, :name)) %>

      <%= f.label :appellation_id %>
      <%= f.select(:appellation_id,options_from_collection_for_select(Appellation.all, :id, :abbreviation)) %>

      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.label :link %>
      <%= f.text_field :link, class: "form-control" %>

      <%= f.label :date_consumed %>
      <%= f.date_field :date_consumed %>

      <%= f.label "Grapes" %>
      <%= f.collection_select :grape_ids , Grape.all, :id, :name, {}, :multiple => true, class: "form-control"  %>

      <h2> Update Picture </h2>
      <HR>
      <%= f.label :picture %>
      <%= f.file_field :picture %>
      <HR>


      <%= f.submit "Update Wine", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<HR>

app/views/wines/index.html.erb
<!-- When submit the form, the view rendered will be the index view of our articles resource -->
<%= form_tag(wines_path, :method => "get", class: "navbar-form", id: "search-form") do %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Wines" %>
    <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
         of using a Rails form helper -->
    <button class="btn" type="submit">Search Wines</button>
  </div>
<% end %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Wine Database</h3>
  </div>
  <div class="panel-body">
    <table class="table table-condensed">
      <tr>
        <th>Name</th>
        <th>Country</th>
        <th>Price</th>
        <th></th>
      </tr>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= link_to wine.name, wine_path(wine.id) %></td>
        <td><%= wine.country.name %></td>
        <% if wine.price %>
          <td><%= wine.price.currency.symbol %><%= wine.price.amount %></td>
        <% else %>
          <td>Unspecified</td>
        <% end %>
        <td><%= link_to "Add to my list", {:controller => "consumed_wines", :action => "new", :wine_id => wine.id }, class: "btn btn-success btn-xs" %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>
<%= button_to 'Add A Wine', new_wine_path, :method => "get", class: "btn btn-success" %>

app/views/wines/new.html.erb
<HR>
<h1>Add a New Wine</h1>

<div>
  <div class="form-group">
    <%= form_for(@wine) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"%>

      <%= f.label :vintage %>
      <%= f.text_field :vintage, class: "form-control" %>

      <%= f.label :country_id %>
      <%= f.select(:country_id,options_from_collection_for_select(Country.all, :id, :name), class: "form-control" ) %>

      <%= f.label :region_id %>
      <%= f.select(:region_id,options_from_collection_for_select(Region.all, :id, :name)) %>

      <%= f.label :appellation_id %>
      <%= f.select(:appellation_id,options_from_collection_for_select(Appellation.all, :id, :abbreviation)) %>

      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.label :link %>
      <%= f.text_field :link, class: "form-control" %>

      <%= f.label :picture %>
      <%= f.file_field :picture %>

      <%= f.label :date_consumed %>
      <%= f.date_field :date_consumed %>

      <%= f.submit "Add Wine", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<HR>

app/views/wines/show.html.erb
<% provide(:title, @wine.name) %>
<p id="notice"><%= notice %></p>
<div>
  <aside class="span4">
    <section>
      <h1><%= @wine.name %></h1>
    </section>
  </aside>
</div>
<div>
  <% if @wine.picture_file_name %>
    <%= image_tag @wine.picture.url(:medium) %>
  <% end %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Wine Details</h3>
    </div>
    <div class="panel-body">
      <p>
        <strong>Description:</strong>
        <% if @wine.description %>
          <%= @wine.description %>
        <% else %>
          Unspecified
        <% end %>
      </p>
      <p>
        <strong>Link:</strong>
        <%= link_to @wine.link, "#{@wine.link}" %>
      </p>
      <% if @wine.date_consumed %>
        <p>
          <strong>Date Consumed:</strong>
          <%= @wine.date_consumed.strftime("%d-%b-%Y") %>
        </p>
      <% end %>
      <% if @wine.country %>
        <p>
          <strong>Country:</strong>
          <%= @wine.country.name %>
        </p>
      <% end %>
      <% if @wine.region %>
        <p>
          <strong>Region:</strong>
          <%= @wine.region.name %>
        </p>
      <% end %>
      <% if @wine.appellation %>
        <p>
          <strong>Appellation:</strong>
          <%= @wine.appellation.name %>
        </p>
      <% end %>
      <% if @wine.vintage %>
        <p>
          <strong>Vintage:</strong>
          <%= @wine.vintage %>
        </p>
      <% end %>
      <p>
        <strong>Grapes:</strong>
          <% @wine.grapes.each do |grape| %>
            <%= grape.name %>,
          <% end %>
      </p>
    </div>
  </div>
</div>

<% if signed_in? %>
<div class="controls text-right">
  <%= link_to "Add to my list", {:controller => "consumed_wines", :action => "new", :wine_id => @wine.id }, class: "btn btn-default" %>
  <%= link_to "Edit", edit_wine_path(@wine), method: :get, class: "btn btn-default" %>
  <%= link_to "Delete Wine", @wine , method: :delete, data: { confirm: "You sure?" }, class: "btn btn-default " %>

<% end %>
</div>
</br>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Wine Reviews</h3>
  </div>

  <div class="panel-body">
    <table class="table table-condensed">
      <% @wine.reviews.each do |review| %>
        <% if review.id %>
          <tr><td>"<%= review.review %>"
            <% if review.user_id %>
              - <%= User.find(review.user_id).name %>
            <% else %>
              - Annon
            <% end %>
         </td></tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>