config/routes.rb
Winedb::Application.routes.draw do

  root  'static_pages#home'
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/contact"
  get "static_pages/about"
  resources :countries
  resources :wines
  resources :grapes
  resources :events
  resources :reviews
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :regions
  resources :collections
  resources :consumed_wines
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/appellation.rb
class Appellation < ActiveRecord::Base
  has_many :wines
  belongs_to :country
end

app/models/consumed_wine.rb
class ConsumedWine < ActiveRecord::Base

  belongs_to :user
  belongs_to :wine
  belongs_to :currency

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :wines
  has_many :regions
  has_many :appellations
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :prices
  has_many :consumed_wines
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :wines
end

app/models/grape.rb
class Grape < ActiveRecord::Base
  has_and_belongs_to_many :wines
end

app/models/price.rb
class Price < ActiveRecord::Base
  validates :amount, presence: true
  validates :wine_id, uniqueness: true
  belongs_to :wine
  belongs_to :currency
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :wines
  belongs_to :country
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :wine
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :wines
  has_many :consumed_wines

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :password, length: { minimum: 6 }
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :country
  belongs_to :region
  belongs_to :appellation
  has_one :price
  has_and_belongs_to_many :events
  has_and_belongs_to_many :grapes
  has_many :reviews
  has_and_belongs_to_many :users
  has_many :consumed_wines

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted."
    redirect_to events_url
  end

  private

    def event_params
      params.require(:event).permit(:name,:description,:date,:wine_ids => [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def edit

  end

  def update

  end

  def index
    @users = User.all
  end

  def destroy

  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/events/edit.html.erb
<h1>Update Wine Event</h1>

<div class="container">
  <div class="form-group">
    <%= form_for(@event) do |f| %>
      <%= f.label "Event Name" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label "Event Description" %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.label :date %>
      <%= f.date_field :date, class: "form-control" %>

      <%= f.label "Wines" %>
      <%= f.collection_select :wine_ids , Wine.all, :id, :name, {}, :multiple => true, class: "form-control"  %>

      <%= f.submit "Update Event", class: "btn btn-large btn-primary form-control" %>
    <% end %>
  </div>
<%= button_to "Delete Event", @event, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger"  %>
</div>

app/views/events/index.html.erb
<div class="container">
  <table class="table ">
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Description</th>
      <th>Delete</th>
    </tr>
  <% @events.each do |event| %>
    <tr>
      <td><%= link_to event.name, event_path(event.id) %></td>
      <td><%= event.date %></td>
      <td><%= event.description %></td>
      <td><%= link_to "Delete", event, method: :delete, data: { confirm: "You sure?" } %> | <%= link_to 'Edit Event', edit_event_path(event), method: :get %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/events/new.html.erb
<h1>Create New Event</h1>

<div class="container">
  <div class="form-group">
    <%= form_for(@event) do |f| %>
      <%= f.label "Event Name" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label "Event Description" %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.label :date %>
      <%= f.date_field :date, class: "form-control" %>

      <%= f.label "Wines" %>
      <%= f.collection_select :wine_ids , Wine.all, :id, :name, {}, :multiple => true, class: "form-control"  %>


      <%= f.submit "Add Event", class: "btn btn-large btn-primary form-control" %>
    <% end %>
  </div>

</div>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>

<div class="container">
  <aside class="span4">
    <section>
      <h1><%= @event.name %></h1>
    </section>
  </aside>
</div>

<p id="notice"><%= notice %></p>

<div class="container">
<h3> Event Description </h3>
<p><% if @event.description %>
  <%= @event.description %>
<% end %>
</p>

<h3>Date </h3>
<% if @event.date %>
<p><%= @event.date.strftime("%d %B %Y") %></p>
<% else %>
<p>Not specified</p>
<% end %>

<h3> Wines </h3>
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>Region</th>
    <th>Price</th>
  </tr>
<% @event.wines.each do |wine| %>
  <tr>
    <td><%= link_to wine.name,  wine_path(wine.id) %></td>
    <td><%= wine.country.name %></td>
    <td><%= wine.region.name %></td>
    <td><%= wine.price.amount %></td>
  </tr>
<% end %>
</table>

<h3> Reviews and Reflections </h3>
<% @event.wines.each do |wine| %>
  <h4><%= link_to wine.name,  wine_path(wine.id) %></h4>
  <table class="table table-striped">
    <% if ! wine.reviews.empty? %>
      <tr>
        <th>Review</th>
      </tr>
      <% wine.reviews.each do |review| %>
        <tr>
          <td><%= review.review %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td>No Reviews</td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= button_to 'Edit Event', edit_event_path(@event), method: :get, class: "btn btn-large btn-primary" %>
</div>