config/routes.rb
Winedb::Application.routes.draw do

  root  'static_pages#home'
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/contact"
  get "static_pages/about"
  resources :countries
  resources :wines
  resources :grapes
  resources :events
  resources :reviews
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :regions
  resources :collections
  resources :consumed_wines
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/appellation.rb
class Appellation < ActiveRecord::Base
  has_many :wines
  belongs_to :country
end

app/models/consumed_wine.rb
class ConsumedWine < ActiveRecord::Base

  belongs_to :user
  belongs_to :wine
  belongs_to :currency

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :wines
  has_many :regions
  has_many :appellations
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :prices
  has_many :consumed_wines
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :wines
end

app/models/grape.rb
class Grape < ActiveRecord::Base
  has_and_belongs_to_many :wines
end

app/models/price.rb
class Price < ActiveRecord::Base
  validates :amount, presence: true
  validates :wine_id, uniqueness: true
  belongs_to :wine
  belongs_to :currency
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :wines
  belongs_to :country
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :wine
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :wines
  has_many :consumed_wines

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :password, length: { minimum: 6 }
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :country
  belongs_to :region
  belongs_to :appellation
  has_one :price
  has_and_belongs_to_many :events
  has_and_belongs_to_many :grapes
  has_many :reviews
  has_and_belongs_to_many :users
  has_many :consumed_wines

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%")
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def new
    @region = Region.new
  end

  def create
    @region = Region.new(region_params)

    if @region.save
      redirect_to @region
    else
      render 'new'
    end
  end

  def edit
    @region = Region.find(params[:id])
  end

  def update
    @region = Region.find(params[:id])

    if @region.update(region_params)
      redirect_to @region
    else
      render 'edit'
    end
  end

  def show
    @region = Region.find(params[:id])
  end

  def index
    @regions = Region.all
  end

  private

    def region_params
      params.require(:region).permit(:country_id, :name, :description)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def edit

  end

  def update

  end

  def index
    @users = User.all
  end

  def destroy

  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/regions/edit.html.erb
<h1>Edit Region</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@region) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :country %>
      <%= f.select(:country_id, options_from_collection_for_select(Country.all, :id, :name, @region.country_id), class: "form-control")  %>

      <%= f.submit "Update Region", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/regions/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Wine Regions</h3>
  </div>
  <div class="panel-body">
    <table class="table table-condensed ">
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Description</th>
    </tr>
  <% @regions.each do |region| %>
    <tr>
      <td><%= link_to region.name, region_path(region.id) %></td>
      <td><%= region.country.name %></td>
      <td><%= region.description %></td>
    </tr>
  <% end %>
  </table>
  </div>
</div>

app/views/regions/new.html.erb
<h1>Create New Region</h1>

<div class="container">
  <div class="span6 offset3">
    <%= form_for(@region) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>

      <%= f.label :country_id %>
      <%= f.collection_select :country_id , Country.all, :id, :name, {}, class: "form-control"  %>

      <%= f.submit "Add Region", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/regions/show.html.erb
<% provide(:title, @region.name) %>

<div class="container">
  <aside class="span4">
    <section>
      <h1>
        <%= @region.name %>
      </h1>
    </section>
  </aside>
</div>

<p id="notice"><%= notice %></p>
<div class="container">
  <p>
    <strong>Description:</strong>
    <%= @region.description %>
  </p>

  <p>
    <strong>Country</strong>
    <%= @region.country.name %>
  </p>

  <%= link_to 'Edit', edit_region_path(@region) %> |
  <%= link_to 'Back', regions_path %>
</div>