config/routes.rb
Winedb::Application.routes.draw do

  root  'static_pages#home'
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/contact"
  get "static_pages/about"
  resources :countries
  resources :wines
  resources :grapes
  resources :events
  resources :reviews
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :regions
  resources :collections
  resources :consumed_wines
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/appellation.rb
class Appellation < ActiveRecord::Base
  has_many :wines
  belongs_to :country
end

app/models/consumed_wine.rb
class ConsumedWine < ActiveRecord::Base

  belongs_to :user
  belongs_to :wine
  belongs_to :currency

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :wines
  has_many :regions
  has_many :appellations
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :prices
  has_many :consumed_wines
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :wines
end

app/models/grape.rb
class Grape < ActiveRecord::Base
  has_and_belongs_to_many :wines
end

app/models/price.rb
class Price < ActiveRecord::Base
  validates :amount, presence: true
  validates :wine_id, uniqueness: true
  belongs_to :wine
  belongs_to :currency
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :wines
  belongs_to :country
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :wine
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :wines
  has_many :consumed_wines

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :password, length: { minimum: 6 }
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :country
  belongs_to :region
  belongs_to :appellation
  has_one :price
  has_and_belongs_to_many :events
  has_and_belongs_to_many :grapes
  has_many :reviews
  has_and_belongs_to_many :users
  has_many :consumed_wines

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("name like ?", "%#{query}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
    Dein Wein Verein
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   static_pages_about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wine Club", root_url, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <% if signed_in? %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_url %></li>
          <li><%= link_to "My Wines", consumed_wines_path %></li>
          <li><%= link_to "Add a new wine", new_consumed_wine_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Wines<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Wine Database", wines_path %></li>
              <li><%= link_to "View Countries", countries_path %></li>
              <li><%= link_to "Wine Regions", regions_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Add Wine", new_wine_path %></li>
              <li><%= link_to "Add Country", new_country_path %></li>
              <li><%= link_to "Add Region", new_region_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Events<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Events", events_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Add Event", new_event_path %></li>
            </ul>
          </li>
        </ul>
      <% else %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_url %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Wines<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Wine Database", wines_path %></li>
              <li><%= link_to "View Countries", countries_path %></li>
              <li><%= link_to "Wine Regions", regions_path %></li>
            </ul>
          </li>
        </ul>
      <% end %>
      <% if signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Account", user_path(current_user) %></li>
            <li><a href="#">My Cellar</a></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
        </li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign in", signin_path %></li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Winedb</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>